---
pull_request_rules:
  - name: Automatic merge on CI success and review
    conditions:
      - approved-reviews-by=xunzhuo
    actions:
      merge:
        method: merge
  - name: ask the maintainer team to review PR
    conditions:
      - and:
        - label!=invalid
        - -draft
    actions:
      request_reviews:
        users:
          - xunzhuo
      assign:
        add_users:
          - xunzhuo
      comment:
        message: |
           Welcome to the UESTC OpenSource Community!👏
           
           Waiting for Maintainer @xunzhuo to check if this PR is valid ⌛️
           
           We're delighted to have you onboard 💘

